import json

notebook_path = 'd:/Sansarana/train_object_detection.ipynb'
with open(notebook_path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

markdown_cell = {
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "# 4. Grounding DINO (Vision-Language Zero-Shot / Fine-Tune)\n",
        "Grounding DINO is an open-vocabulary detector. We don't train it on numbers (0, 1, 2), we prompt it with **Text Strings**. To fit on your 12GB RTX 4070 SUPER, we will freeze the massive vision models and only unfreeze the bounding box predictor heads to fine-tune it dynamically on your YOLO dataset!"
    ]
}

code_cell = {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "!pip install -q transformers peft\n",
        "import os\n",
        "import torch\n",
        "from PIL import Image\n",
        "from torch.utils.data import DataLoader, Dataset\n",
        "from tqdm import tqdm\n",
        "from transformers import AutoProcessor, AutoModelForZeroShotObjectDetection\n",
        "\n",
        "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
        "\n",
        "# 1. Define Visual-Language Prompt mapping from YOLO IDs\n",
        "# RT-DETR YOLO data.yaml: 0: reclining, 1: seated, 2: standing\n",
        "# We bundle them into a single tokenized prompt sentence:\n",
        "TEXT_PROMPT = \"reclining statue. seated statue. standing statue.\"\n",
        "YOLO_TO_DINO_CLASS = {0: 0, 1: 1, 2: 2} # The positional index of the phrase in the prompt\n",
        "\n",
        "print(\"Loading Base Grounding DINO Processor...\")\n",
        "processor = AutoProcessor.from_pretrained(\"IDEA-Research/grounding-dino-base\")\n",
        "\n",
        "class YOLOToGroundingDINODataset(Dataset):\n",
        "    def __init__(self, images_dir, labels_dir):\n",
        "        self.images_dir = images_dir\n",
        "        self.labels_dir = labels_dir\n",
        "        self.images = [f for f in os.listdir(images_dir) if f.endswith(('.jpg', '.png'))]\n",
        "        \n",
        "    def __len__(self):\n",
        "        return len(self.images)\n",
        "        \n",
        "    def __getitem__(self, idx):\n",
        "        img_name = self.images[idx]\n",
        "        base_name = os.path.splitext(img_name)[0]\n",
        "        img_path = os.path.join(self.images_dir, img_name)\n",
        "        label_path = os.path.join(self.labels_dir, base_name + '.txt')\n",
        "        \n",
        "        image = Image.open(img_path).convert(\"RGB\")\n",
        "        w, h = image.size\n",
        "        \n",
        "        boxes = []\n",
        "        class_labels = []\n",
        "        \n",
        "        if os.path.exists(label_path):\n",
        "            with open(label_path, 'r') as f:\n",
        "                for line in f.readlines():\n",
        "                    parts = line.strip().split()\n",
        "                    if len(parts) >= 5:\n",
        "                        cls_id = int(parts[0])\n",
        "                        # Grounding DINO in huggingface processors currently expects unnormalized [xmin, ymin, xmax, ymax] \n",
        "                        # before processor encoding, so we convert YOLO [cx, cy, w, h] normalized back to absolute pixels.\n",
        "                        cx, cy, bw, bh = map(float, parts[1:5])\n",
        "                        xmin = (cx - bw / 2) * w\n",
        "                        ymin = (cy - bh / 2) * h\n",
        "                        xmax = (cx + bw / 2) * w\n",
        "                        ymax = (cy + bh / 2) * h\n",
        "                        \n",
        "                        if cls_id in YOLO_TO_DINO_CLASS:\n",
        "                            boxes.append([xmin, ymin, xmax, ymax])\n",
        "                            class_labels.append(YOLO_TO_DINO_CLASS[cls_id])\n",
        "                            \n",
        "        # Pre-process the image and textual prompt!\n",
        "        inputs = processor(images=image, text=TEXT_PROMPT, return_tensors=\"pt\")\n",
        "        inputs = {k: v.squeeze(0) for k, v in inputs.items()} # remove batch dim from processor\n",
        "        \n",
        "        # Huggingface targets require unscaled dictionary formatting\n",
        "        target = {}\n",
        "        if boxes:\n",
        "            target[\"boxes\"] = torch.tensor(boxes, dtype=torch.float32)\n",
        "            target[\"class_labels\"] = torch.tensor(class_labels, dtype=torch.long)\n",
        "        else:\n",
        "            target[\"boxes\"] = torch.zeros((0, 4), dtype=torch.float32)\n",
        "            target[\"class_labels\"] = torch.zeros((0,), dtype=torch.long)\n",
        "            \n",
        "        return inputs, target\n",
        "\n",
        "def dino_collate_fn(batch):\n",
        "    input_ids = torch.stack([x[0]['input_ids'] for x in batch])\n",
        "    attention_mask = torch.stack([x[0]['attention_mask'] for x in batch])\n",
        "    pixel_values = torch.stack([x[0]['pixel_values'] for x in batch])\n",
        "    labels = [x[1] for x in batch]\n",
        "    \n",
        "    return {\n",
        "        'input_ids': input_ids,\n",
        "        'attention_mask': attention_mask,\n",
        "        'pixel_values': pixel_values,\n",
        "        'labels': labels\n",
        "    }\n",
        "\n",
        "# 2. Build Efficient Dataloaders\n",
        "yolo_train = YOLOToGroundingDINODataset(\n",
        "    r'd:\\Sansarana\\RT-DETR\\train\\images',\n",
        "    r'd:\\Sansarana\\RT-DETR\\train\\labels'\n",
        ")\n",
        "dino_loader = DataLoader(yolo_train, batch_size=2, shuffle=True, collate_fn=dino_collate_fn, num_workers=0)\n",
        "\n",
        "# 3. Load HuggingFace DINO and Freeze Vision Backbone\n",
        "print(\"Loading Grounding DINO Model Weights (This may take a minute)...\")\n",
        "dino_model = AutoModelForZeroShotObjectDetection.from_pretrained(\n",
        "    \"IDEA-Research/grounding-dino-base\", \n",
        "    ignore_mismatched_sizes=True\n",
        ")\n",
        "\n",
        "# CRITICAL: Freeze entire Swin Transformer & BERT so it doesn't crash your 12GB VRAM\n",
        "for param in dino_model.backbone.parameters():\n",
        "    param.requires_grad = False\n",
        "for param in dino_model.text_backbone.parameters():\n",
        "    param.requires_grad = False\n",
        "    \n",
        "dino_model = dino_model.to(device)\n",
        "optimizer = torch.optim.AdamW(filter(lambda p: p.requires_grad, dino_model.parameters()), lr=1e-5)\n",
        "\n",
        "# 4. Custom DINO Fine-Tuning Loop\n",
        "num_epochs = 5\n",
        "scaler = torch.amp.GradScaler('cuda')\n",
        "dino_model.train()\n",
        "\n",
        "print(f\"🔥 Starting Grounding DINO Visual-Language Tuning on {len(yolo_train)} YOLO Images... 🔥\")\n",
        "for epoch in range(num_epochs):\n",
        "    epoch_loss = 0.0\n",
        "    with tqdm(dino_loader, desc=f\"Epoch {epoch+1}/{num_epochs}\") as pbar:\n",
        "        for batch in pbar:\n",
        "            input_ids = batch['input_ids'].to(device)\n",
        "            attention_mask = batch['attention_mask'].to(device)\n",
        "            pixel_values = batch['pixel_values'].to(device)\n",
        "            labels = [{k: v.to(device) for k, v in t.items()} for t in batch['labels']]\n",
        "            \n",
        "            optimizer.zero_grad(set_to_none=True)\n",
        "            \n",
        "            # AMP Forward Pass natively calculates cross-entropy loss against the provided text prompt mapping\n",
        "            with torch.amp.autocast('cuda'):\n",
        "                outputs = dino_model(input_ids=input_ids, attention_mask=attention_mask, pixel_values=pixel_values, labels=labels)\n",
        "                loss = outputs.loss\n",
        "                \n",
        "            scaler.scale(loss).backward()\n",
        "            # Gradient clipping is highly recommended for DINO transformer heads to prevent explosion\n",
        "            scaler.unscale_(optimizer)\n",
        "            torch.nn.utils.clip_grad_norm_(dino_model.parameters(), 1.0)\n",
        "            \n",
        "            scaler.step(optimizer)\n",
        "            scaler.update()\n",
        "            \n",
        "            epoch_loss += loss.item()\n",
        "            pbar.set_postfix(loss=f\"{loss.item():.4f}\")\n",
        "            \n",
        "    print(f\"Epoch {epoch+1} Average Loss: {epoch_loss/len(dino_loader):.4f}\")\n",
        "\n",
        "torch.save(dino_model.state_dict(), r'd:\\Sansarana\\dino_tuned_final.pth')\n",
        "print(\"Grounding DINO Fine-Tuning Completed!\")\n"
    ]
}

nb['cells'].extend([markdown_cell, code_cell])

with open(notebook_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1)
