import json

notebook_path = 'd:/Sansarana/train_object_detection.ipynb'
with open(notebook_path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

# Find where the previously added cell is, to override it
if nb['cells'][-1]['source'][0].startswith('!pip install -q effdet'):
    nb['cells'].pop()
    nb['cells'].pop()

markdown_cell = {
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "# 3. EfficientDet (VOC Format)\n",
        "Next, we will train an **EfficientDet** model using the `effdet` package on your Pascal VOC dataset."
    ]
}

code_cell = {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "!pip install -q effdet omegaconf\n",
        "import os\n",
        "import xml.etree.ElementTree as ET\n",
        "import torch\n",
        "from PIL import Image\n",
        "from torch.utils.data import DataLoader, Dataset\n",
        "import torchvision.transforms.functional as F\n",
        "from tqdm import tqdm\n",
        "from effdet.factory import create_model\n",
        "\n",
        "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
        "\n",
        "# 1. Define Dataset Mapping\n",
        "CLASS_MAP = {'seated': 1, 'standing': 2, 'reclining': 3}\n",
        "\n",
        "# 2. PyTorch VOC Dataset for EfficientDet\n",
        "class EffDetVOCDataset(Dataset):\n",
        "    def __init__(self, root_dir):\n",
        "        self.root_dir = root_dir\n",
        "        self.files = [f.split('.xml')[0] for f in os.listdir(root_dir) if f.endswith('.xml')]\n",
        "        \n",
        "    def __len__(self):\n",
        "        return len(self.files)\n",
        "        \n",
        "    def __getitem__(self, idx):\n",
        "        file_id = self.files[idx]\n",
        "        img_path = os.path.join(self.root_dir, file_id + '.jpg')\n",
        "        xml_path = os.path.join(self.root_dir, file_id + '.xml')\n",
        "        \n",
        "        img = Image.open(img_path).convert('RGB')\n",
        "        img_tensor = F.to_tensor(img)\n",
        "        \n",
        "        tree = ET.parse(xml_path)\n",
        "        root = tree.getroot()\n",
        "        \n",
        "        boxes = []\n",
        "        labels = []\n",
        "        for obj in root.findall('object'):\n",
        "            name = obj.find('name').text\n",
        "            if name not in CLASS_MAP:\n",
        "                continue\n",
        "            labels.append(CLASS_MAP[name])\n",
        "            \n",
        "            bndbox = obj.find('bndbox')\n",
        "            xmin = float(bndbox.find('xmin').text)\n",
        "            ymin = float(bndbox.find('ymin').text)\n",
        "            xmax = float(bndbox.find('xmax').text)\n",
        "            ymax = float(bndbox.find('ymax').text)\n",
        "            # EfficientDet natively expects standard (y_min, x_min, y_max, x_max)\n",
        "            boxes.append([ymin, xmin, ymax, xmax]) \n",
        "        \n",
        "        # Targets must be correctly padded for DataLoader stack\n",
        "        target = {\n",
        "            'bbox': torch.tensor(boxes, dtype=torch.float32) if boxes else torch.zeros((0,4)),\n",
        "            'cls': torch.tensor(labels, dtype=torch.int64)\n",
        "        }\n",
        "        return img_tensor, target\n",
        "\n",
        "def effdet_collate(batch):\n",
        "    images = torch.stack([b[0] for b in batch])\n",
        "    targets = [b[1] for b in batch]\n",
        "    # Convert targets to the format EfficientDet train bench requires:\n",
        "    # It heavily expects 'bbox' to be shape [batch_size, num_targets, 4]\n",
        "    # Which means we need to pad the bounding boxes across batch dimension!\n",
        "    max_targets = max([t['bbox'].shape[0] for t in targets])\n",
        "    \n",
        "    padded_bboxes = torch.zeros((len(targets), max_targets, 4))\n",
        "    padded_classes = torch.zeros((len(targets), max_targets), dtype=torch.int64) - 1  # -1 for empty\n",
        "    \n",
        "    for i, t in enumerate(targets):\n",
        "        m = t['bbox'].shape[0]\n",
        "        if m > 0:\n",
        "            padded_bboxes[i, :m] = t['bbox']\n",
        "            padded_classes[i, :m] = t['cls']\n",
        "            \n",
        "    batch_targets = {'bbox': padded_bboxes, 'cls': padded_classes}\n",
        "    return images, batch_targets\n",
        "\n",
        "# Instantiate Loader\n",
        "train_set = EffDetVOCDataset(r'd:\\Sansarana\\EfficientDetVOC\\train')\n",
        "eff_loader = DataLoader(train_set, batch_size=4, shuffle=True, collate_fn=effdet_collate, num_workers=0)\n",
        "\n",
        "# 3. Create Model\n",
        "print(\"Building EfficientDet...\")\n",
        "effdet_model = create_model('tf_efficientdet_d0', bench_task='train', num_classes=3, pretrained=True)\n",
        "effdet_model = effdet_model.to(device)\n",
        "\n",
        "# 4. Training Setup\n",
        "optimizer = torch.optim.AdamW(effdet_model.parameters(), lr=1e-4)\n",
        "\n",
        "# 5. Training Loop\n",
        "effdet_model.train()\n",
        "num_epochs = 15\n",
        "scaler = torch.amp.GradScaler('cuda')\n",
        "\n",
        "print(f\"Staring EfficientDet training on {len(train_set)} images...\")\n",
        "for epoch in range(num_epochs):\n",
        "    epoch_loss = 0.0\n",
        "    with tqdm(eff_loader, desc=f\"Epoch {epoch+1}/{num_epochs}\") as pbar:\n",
        "        for images, targets in pbar:\n",
        "            images = images.to(device)\n",
        "            targets = {\n",
        "                'bbox': targets['bbox'].to(device),\n",
        "                'cls': targets['cls'].to(device)\n",
        "            }\n",
        "            \n",
        "            optimizer.zero_grad(set_to_none=True)\n",
        "            \n",
        "            with torch.amp.autocast('cuda'):\n",
        "                loss_dict = effdet_model(images, targets)\n",
        "                loss = loss_dict['loss']\n",
        "                \n",
        "            scaler.scale(loss).backward()\n",
        "            scaler.step(optimizer)\n",
        "            scaler.update()\n",
        "            \n",
        "            epoch_loss += loss.item()\n",
        "            pbar.set_postfix(loss=loss.item())\n",
        "            \n",
        "    print(f\"Epoch {epoch+1} Average Loss: {epoch_loss/len(eff_loader):.4f}\")\n",
        "\n",
        "torch.save(effdet_model.state_dict(), r'd:\\Sansarana\\efficientdet_final.pth')\n",
        "print(\"EfficientDet training completed and model saved!\")\n"
    ]
}

nb['cells'].extend([markdown_cell, code_cell])

with open(notebook_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1)
