import json

notebook_path = 'd:/Sansarana/train_object_detection.ipynb'
with open(notebook_path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

# Find and replace the comparison cell
for cell in nb['cells']:
    if cell.get('cell_type') == 'code' and 'import pandas as pd' in ''.join(cell.get('source', [])):
        cell['source'] = [
            "!pip install -q pandas\n",
            "import pandas as pd\n",
            "import json, datetime\n",
            "from IPython.display import display, HTML\n",
            "\n",
            "# ============================================================\n",
            "# MODEL COMPARISON TABLE\n",
            "# RT-DETR scores are auto-read from results.csv.\n",
            "# Fill in mAP scores for other models after running their eval cells.\n",
            "# ============================================================\n",
            "\n",
            "# --- Auto-read RT-DETR best epoch from results.csv ---\n",
            "import csv\n",
            "rtdetr_csv = r'd:\\Sansarana\\runs\\detect\\rtdetr_custom_training\\run_1\\results.csv'\n",
            "best_map50, best_map5095 = 0.0, 0.0\n",
            "with open(rtdetr_csv) as f:\n",
            "    reader = csv.DictReader(f)\n",
            "    for row in reader:\n",
            "        try:\n",
            "            m50 = float(row['metrics/mAP50(B)'].strip())\n",
            "            m5095 = float(row['metrics/mAP50-95(B)'].strip())\n",
            "            if m5095 > best_map5095:\n",
            "                best_map50 = m50\n",
            "                best_map5095 = m5095\n",
            "        except (ValueError, KeyError):\n",
            "            continue\n",
            "print(f'RT-DETR best mAP@50: {best_map50:.4f} | mAP@50-95: {best_map5095:.4f}')\n",
            "\n",
            "# ---------------------------------------------------------------\n",
            "# Paste your evaluation cell scores for the other models below:\n",
            "# ---------------------------------------------------------------\n",
            "results = {\n",
            "    'RT-DETR (Large)': {\n",
            "        'mAP@50':         best_map50,    # auto-loaded\n",
            "        'mAP@75':         None,          # not available from YOLO CSV\n",
            "        'mAP (0.5:0.95)': best_map5095,  # auto-loaded\n",
            "        'Epochs':         50,\n",
            "        'Backbone':       'ResNet-50-DC5 + Transformer',\n",
            "        'Format':         'YOLO TXT',\n",
            "    },\n",
            "    'Faster R-CNN (ResNet-50 FPN)': {\n",
            "        'mAP@50':         None,   # <- paste from evaluation cell\n",
            "        'mAP@75':         None,\n",
            "        'mAP (0.5:0.95)': None,\n",
            "        'Epochs':         15,\n",
            "        'Backbone':       'ResNet-50 + FPN',\n",
            "        'Format':         'COCO JSON',\n",
            "    },\n",
            "    'EfficientDet (D0)': {\n",
            "        'mAP@50':         None,\n",
            "        'mAP@75':         None,\n",
            "        'mAP (0.5:0.95)': None,\n",
            "        'Epochs':         15,\n",
            "        'Backbone':       'EfficientNet-B0 + BiFPN',\n",
            "        'Format':         'Pascal VOC XML',\n",
            "    },\n",
            "    'Grounding DINO (Base)': {\n",
            "        'mAP@50':         None,\n",
            "        'mAP@75':         None,\n",
            "        'mAP (0.5:0.95)': None,\n",
            "        'Epochs':         5,\n",
            "        'Backbone':       'Swin-T + BERT (frozen)',\n",
            "        'Format':         'YOLO TXT',\n",
            "    },\n",
            "}\n",
            "\n",
            "# ---- Render table ----\n",
            "rows = []\n",
            "for model_name, scores in results.items():\n",
            "    def fmt(v):\n",
            "        return f'{v:.4f}' if isinstance(v, float) else (str(v) if v is not None else 'N/A')\n",
            "    rows.append({\n",
            "        'Model':            model_name,\n",
            "        'Backbone':         scores['Backbone'],\n",
            "        'Dataset Format':   scores['Format'],\n",
            "        'Epochs':           scores['Epochs'],\n",
            "        'mAP@50':           fmt(scores['mAP@50']),\n",
            "        'mAP@75':           fmt(scores['mAP@75']),\n",
            "        'mAP (0.5:0.95)':   fmt(scores['mAP (0.5:0.95)']),\n",
            "    })\n",
            "\n",
            "df = pd.DataFrame(rows).set_index('Model')\n",
            "\n",
            "def highlight_best(col):\n",
            "    numeric = pd.to_numeric(col, errors='coerce')\n",
            "    best = numeric.max()\n",
            "    return ['background-color: #27ae60; color: white; font-weight: bold'\n",
            "            if pd.notna(v) and v == best else '' for v in numeric]\n",
            "\n",
            "styled = (\n",
            "    df.style\n",
            "    .apply(highlight_best, subset=['mAP@50', 'mAP@75', 'mAP (0.5:0.95)'])\n",
            "    .set_caption('📊 Object Detection Model Comparison — Sansarana Statue Dataset')\n",
            "    .set_table_styles([{\n",
            "        'selector': 'caption',\n",
            "        'props': [('font-size', '16px'), ('font-weight', 'bold'), ('margin-bottom', '8px')]\n",
            "    }, {\n",
            "        'selector': 'th',\n",
            "        'props': [('background-color', '#2c3e50'), ('color', 'white'),\n",
            "                  ('padding', '10px'), ('text-align', 'center')]\n",
            "    }, {\n",
            "        'selector': 'td',\n",
            "        'props': [('padding', '10px'), ('text-align', 'center'), ('border', '1px solid #ddd')]\n",
            "    }])\n",
            ")\n",
            "\n",
            "display(styled)\n",
            "\n",
            "report = {\n",
            "    'generated': datetime.datetime.now().isoformat(),\n",
            "    'dataset': 'Sansarana Statue Dataset',\n",
            "    'classes': ['seated', 'standing', 'reclining'],\n",
            "    'models': {k: {mk: (round(mv, 4) if isinstance(mv, float) else mv)\n",
            "                   for mk, mv in v.items()} for k, v in results.items()}\n",
            "}\n",
            "with open(r'd:\\Sansarana\\model_comparison_report.json', 'w') as f:\n",
            "    json.dump(report, f, indent=2)\n",
            "print('\\nSaved to model_comparison_report.json')\n"
        ]
        break

with open(notebook_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1)
print("Done.")
